### ISSUE TITLE
error pls help

### ISSUE THREAD

**Issue by bmohamedfaizal** [guardianproject/OrbotVPN#1]
```
at org.torproject.android.vpn.OrbotVpnService.handshake(OrbotVpnService.java:327)
at org.torproject.android.vpn.OrbotVpnService.run(OrbotVpnService.java:208)
at org.torproject.android.vpn.OrbotVpnService.run(OrbotVpnService.java:127)
```

Got java.lang.IllegalStateException: command '58 interface fwmark rule add tun0' failed with '400 58 Failed to add fwmark rule (File exists)'

while try to build this app i had error pls help ?????

**Comment by patcon** [comment]
This seems the same as my #3, which I think is related to running on an emulator:
https://github.com/guardianproject/OrbotVPN/issues/3#issuecomment-57548831

I think this can be closed.
